// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfoniaxhnzbwcsmvmdqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmb25pYXhobnpid2NzbXZtZHFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2MTEyMDUsImV4cCI6MjA1NzE4NzIwNX0.4uf7dBZ5w38aDcuEPC87ci8G-Ov6bZ91ONwMBpakU6E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);